/** @type {import('./types.js').LayoutDefinition[]} */
export const LAYOUT_DEFINITIONS = [
  {
    id: 'sidebar-accent-right',
    name: 'Sidebar Right · Classic',
    body: 'sidebar-right',
    header: 'standard',
    photo: 'header',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'grid-two-col',
    sectionTitleMain: 'bar',
    sectionTitleSidebar: 'caps',
    skills: 'tags',
    sidebarOrder: ['photo', 'languages', 'coreCompetencies', 'toolsDelivery', 'certifications', 'sabbatical'],
    mainOrder: ['profile', 'employment', 'education', 'references', 'availability'],
  },
  {
    id: 'sidebar-filled-left',
    name: 'Sidebar Left · Filled Panel',
    body: 'sidebar-left',
    header: 'standard',
    photo: 'sidebar',
    employment: 'standard',
    referencesZone: 'sidebar',
    referenceStyle: 'sidebar-card',
    sectionTitleMain: 'underline',
    sectionTitleSidebar: 'caps',
    skills: 'tags',
    contactInSidebar: true,
    sidebarOrder: ['photo', 'contact', 'languages', 'coreCompetencies', 'toolsDelivery', 'certifications', 'references', 'sabbatical'],
    mainOrder: ['profile', 'employment', 'education', 'availability'],
  },
  {
    id: 'header-band-duo',
    name: 'Full-Width Band · Two Column',
    body: 'sidebar-right',
    header: 'band',
    photo: 'header',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'stacked',
    sectionTitleMain: 'pill',
    sectionTitleSidebar: 'caps',
    skills: 'tags',
    sidebarOrder: ['languages', 'coreCompetencies', 'toolsDelivery', 'certifications'],
    mainOrder: ['profile', 'employment', 'education', 'references', 'availability'],
  },
  {
    id: 'hero-centered',
    name: 'Centered Hero · Single Flow',
    body: 'single',
    header: 'centered',
    photo: 'hero',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'stacked',
    sectionTitleMain: 'italic',
    skills: 'list',
    langDisplay: 'text',
    mainOrder: ['profile', 'employment', 'education', 'coreCompetencies', 'toolsDelivery', 'languages', 'references', 'availability'],
  },
  {
    id: 'timeline-editorial',
    name: 'Timeline · Editorial',
    body: 'sidebar-right',
    header: 'standard',
    photo: 'header',
    employment: 'timeline',
    referencesZone: 'main',
    referenceStyle: 'grid-two-col',
    sectionTitleMain: 'underline',
    sectionTitleSidebar: 'caps',
    skills: 'tags',
    langDisplay: 'bars',
    sidebarOrder: ['languages', 'coreCompetencies', 'toolsDelivery', 'certifications'],
    mainOrder: ['profile', 'employment', 'education', 'references', 'availability'],
  },
  {
    id: 'profile-hero-split',
    name: 'Hero Card · Timeline & Split Refs',
    body: 'sidebar-right',
    header: 'hero-card',
    photo: 'header',
    employment: 'timeline',
    referencesZone: 'main',
    referenceStyle: 'grid-two-col',
    sectionTitleMain: 'plain',
    sectionTitleSidebar: 'caps',
    skills: 'dots',
    langDisplay: 'bars',
    summaryInHeader: true,
    sidebarOrder: ['languages', 'coreCompetencies', 'toolsDelivery', 'certifications'],
    mainOrder: ['employment', 'education', 'references', 'availability'],
  },
  {
    id: 'functional-skills-first',
    name: 'Skills-First · Functional',
    body: 'single',
    header: 'standard',
    photo: 'header',
    employment: 'cards',
    referencesZone: 'main',
    referenceStyle: 'stacked',
    sectionTitleMain: 'bar',
    skills: 'list',
    skillsInMain: true,
    langDisplay: 'bars',
    mainOrder: ['coreCompetencies', 'toolsDelivery', 'profile', 'employment', 'education', 'references', 'availability'],
  },
  {
    id: 'magazine-split',
    name: 'Magazine · Center Split',
    body: 'center-split',
    header: 'minimal',
    photo: 'header',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'stacked',
    sectionTitleMain: 'italic',
    skills: 'list',
    langDisplay: 'text',
    mainOrder: ['profile', 'employment'],
  },
  {
    id: 'ats-minimal',
    name: 'ATS · Minimal Single',
    body: 'single',
    header: 'minimal',
    photo: 'none',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'stacked',
    sectionTitleMain: 'minimal',
    skills: 'list',
    langDisplay: 'text',
    mainOrder: ['profile', 'employment', 'coreCompetencies', 'toolsDelivery', 'education', 'references', 'availability'],
  },
  {
    id: 'card-modern',
    name: 'Card Stack · Tech Sidebar',
    body: 'sidebar-right',
    header: 'split',
    photo: 'sidebar',
    employment: 'cards',
    referencesZone: 'sidebar',
    referenceStyle: 'sidebar-card',
    sectionTitleMain: 'plain',
    sectionTitleSidebar: 'caps',
    skills: 'dots',
    langDisplay: 'dots',
    sidebarOrder: ['photo', 'coreCompetencies', 'toolsDelivery', 'languages', 'certifications', 'references'],
    mainOrder: ['profile', 'employment', 'education', 'availability'],
  },
  {
    id: 'contrast-panel',
    name: 'Contrast Panel · Bordered Sidebar',
    body: 'sidebar-right',
    header: 'standard',
    photo: 'header',
    employment: 'standard',
    referencesZone: 'main',
    referenceStyle: 'grid-two-col',
    sectionTitleMain: 'pill',
    sectionTitleSidebar: 'underline',
    skills: 'tags',
    sidebarOrder: ['languages', 'coreCompetencies', 'toolsDelivery', 'certifications'],
    mainOrder: ['profile', 'employment', 'education', 'references', 'availability'],
  },
  {
    id: 'dark-banner-left',
    name: 'Dark Band · Left Sidebar',
    body: 'sidebar-left',
    header: 'dark-band',
    photo: 'sidebar',
    employment: 'standard',
    referencesZone: 'sidebar',
    referenceStyle: 'sidebar-card',
    sectionTitleMain: 'bar',
    sectionTitleSidebar: 'caps',
    skills: 'tags',
    contactInSidebar: true,
    sidebarOrder: ['photo', 'contact', 'coreCompetencies', 'toolsDelivery', 'languages', 'certifications', 'references'],
    mainOrder: ['profile', 'employment', 'education', 'availability'],
  },
];

const byId = new Map(LAYOUT_DEFINITIONS.map((l) => [l.id, l]));

export function getLayoutDefinition(id) {
  return byId.get(id) ?? byId.get('sidebar-accent-right');
}

export function listLayoutDefinitions() {
  return LAYOUT_DEFINITIONS;
}
